# Dockerfile
FROM python:3.10-slim

# Avoiding problems with pyc
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# set working directory
WORKDIR /app

# Install system dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Expose the port the app runs on
EXPOSE 3006  

# Execute the application
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "3006"]
