# Dockerfile
FROM python:3.10-slim

# Evita problemas con pyc
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Establecer directorio de trabajo
WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto de archivos del microservicio
COPY . .

# Exponer puerto (opcional - solo informativo)
EXPOSE 3006  

# Ejecutar FastAPI con Uvicorn
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "3006"]
