name: Build and Deploy to EC2

on:
  push:
    branches:
      - QA

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 2: Configurar Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Paso 3: Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Paso 4: Construir y subir las imágenes Docker
    - name: Build and push Docker images
      run: |
        docker build -t alexmpz/change-password-service:qa ./change-password
        docker build -t alexmpz/validate-token-service:qa ./validate-token
        docker build -t alexmpz/login-user-service:qa ./login-user
        docker build -t alexmpz/register-user-service:qa ./register-user
        docker push alexmpz/change-password-service:qa
        docker push alexmpz/validate-token-service:qa
        docker push alexmpz/login-user-service:qa
        docker push alexmpz/register-user-service:qa

    # Paso 5: Conectar a la instancia EC2 usando IP elástica y desplegar los contenedores
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOSTT }}  # Usar la IP elástica de EC2 aquí
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          # Descargar las imágenes desde Docker Hub
          docker pull alexmpz/change-password-service:qa
          docker pull alexmpz/validate-token-service:qa
          docker pull alexmpz/login-user-service:qa
          docker pull alexmpz/register-user-service:qa
          
          # Ejecutar los contenedores en los puertos específicos
          docker run -d -p 3009:3009 alexmpz/change-password-service:qaa
          docker run -d -p 3007:3007 alexmpz/login-user-service:qa
          docker run -d -p 3006:3006 alexmpz/register-user-service:qa
          docker run -d -p 3008:3008 alexmpz/validate-token-service:qa
